global:
 scrape_interval: 5s

rule_files:
  - alert.yml

scrape_configs:
 - job_name: 'prometheus'
   scrape_interval: 5s
   static_configs:
    - targets: ['localhost:9090']
 - job_name: 'node-explorer'
   scrape_interval: 1s
   static_configs:
     - targets: ['node-exporter:9100']
 - job_name: 'api-prediction'
   scrape_interval: 1s
   static_configs:
     - targets: ['api-prediction:5000']