# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os

new_path = 'D:\Loh\Driver\chromedriver_win32'
existing_path = os.environ['PATH']
os.environ['PATH'] = new_path + os.pathsep + existing_path

class TestMLOPSfronttest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mLOPSfronttest(self):
    self.driver.get("http://localhost:5001/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("Cowboy Bebop")
    self.driver.find_element(By.ID, "synopsis").click()
    self.driver.find_element(By.ID, "synopsis").send_keys("In the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet Earth behind")
    self.driver.find_element(By.NAME, "type").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(6) > option:nth-child(1)").click()
    dropdown = self.driver.find_element(By.NAME, "genres")
    dropdown.find_element(By.XPATH, "//option[. = 'action']").click()
    dropdown = self.driver.find_element(By.NAME, "genres")
    dropdown.find_element(By.XPATH, "//option[. = 'adventure']").click()
    dropdown = self.driver.find_element(By.NAME, "genres")
    dropdown.find_element(By.XPATH, "//option[. = 'comedy']").click()
    dropdown = self.driver.find_element(By.NAME, "genres")
    dropdown.find_element(By.XPATH, "//option[. = 'drama']").click()
    dropdown = self.driver.find_element(By.NAME, "genres")
    dropdown.find_element(By.XPATH, "//option[. = 'sci-fi']").click()
    dropdown = self.driver.find_element(By.NAME, "genres")
    dropdown.find_element(By.XPATH, "//option[. = 'space']").click()
    self.driver.find_element(By.NAME, "producers").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(10) > option:nth-child(1)").click()
    dropdown = self.driver.find_element(By.NAME, "studio")
    dropdown.find_element(By.XPATH, "//option[. = 'Sunrise']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(13)").click()
  
